name: hwr_env
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.8.5
- anaconda::pip=20.2.2
- anaconda::pyyaml=5.3.1
- anaconda::pandas=1.1.1
- conda-forge::matplotlib=3.3.2
- anaconda::tqdm=4.38.0
- conda-forge::editdistance=0.5.3
- pip:
    - tensorflow-gpu==2.3.0
