name: hwr_env
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.7.3
- anaconda::tensorflow-gpu=2.1.0
- anaconda::pandas=1.0.3
- conda-forge::matplotlib=3.2.1
- anaconda::pillow=7.1.2
- anaconda::tqdm=4.31.1
- conda-forge::editdistance=0.5.3
