package:
  name: hwr
  version: 0.1

source:
  git_rev: master
  git_url: https://github.com/BYU-Handwriting-Lab/HandwritingRecognition.git

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python==3.7.3
    - tensorflow==2.1.0
    - pandas==1.0.3
    - pillow==7.1.2
    - matplotlib==3.2.1
    - tqdm==4.38
  run:
    - python==3.7.3
    - tensorflow==2.1.0
    - pandas==1.0.3
    - pillow==7.1.2
    - matplotlib==3.2.1
    - tqdm==4.38

test:
  imports:
    - hwr

about:
  home: https://github.com/BYU-Handwriting-Lab
