# Train Configuration File

# The path to a tab-delimited CSV file containing training data information formatted as | IMG_PATH | Transcription |
train_csv_path: ./data/example/labels.csv
# The path to a tab-delimited CSV file containing validation data information formatted as | IMG_PATH | Transcription |
val_csv_path:
# The ratio used to determine the size of the train/validation split. If split_train_size is set to 0.8, then the
# training set will contain 80% of the data, and validation 20%. The dataset is not shuffled before being split.
split_train_size: 0.8
# Apply data augmentation to the training dataset
augmentation: True

# The path to store the trained model weights
model_out: ./data/model_weights/example_model/run1
# The path to pre-trained model weights
model_in:

# The number of epochs to train
epochs: 100
# The number of images in a mini-batch
batch_size: 10
# The learning rate the optimizer uses during training
learning_rate: 0.001  # DO NOT use scientific notation! Pyyaml interprets scientific notation as string.
# The max number of characters in a line-level transcription
max_seq_size: 128
# The size which all images will be resized - (height, width)
img_size: (64, 1024)

# String including the character set for the model (charset: abcd1234) If no characters are specified, the default is used.
charset: